name: GitHub Readme Stats
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - main

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  generate-stats:
    strategy:
      matrix:
        theme: [light, github_dark]
    permissions:
      contents: write
    # permissions: write-all
    runs-on: ubuntu-latest
    name: Generate stats cards
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate stats-${{ matrix.theme }}
        uses: Jacobus-afk/grs-action@master
        id: generate
        with:
          card: stats
          # options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&include_all_commits=true&number_format=long&hide_title=true&show=discussions_started&hide_border=true&disable_animations=false&hide_rank=true&theme=${{ matrix.theme }}
          options: username=${{ github.repository_owner }}&count_private=true&show=discussions_started,discussions_answered&theme=${{ matrix.theme }}&show_icons=true&rank_icon=github&hide_rank=true&hide_title=true&text_bold=false&hide_border=false&border_color=3d444d&bg_color=00000000
          path: grs/stats-${{ matrix.theme }}.svg

      - name: Upload stats-${{ matrix.theme }}
        uses: actions/upload-artifact@v4
        with:
          name: stats-${{ matrix.theme }}
          path: grs

  generate-langs:
    strategy:
      matrix:
        theme: [light, github_dark]
    # permissions: write-all
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Generate top language cards
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate stats-${{ matrix.theme }}
        uses: Jacobus-afk/grs-action@master
        id: generate
        with:
          card: langs
          options: username=${{ github.repository_owner }}&show_icons=true&theme=${{ matrix.theme }}&hide_title=true&hide=javascript&layout=compact&langs_count=8&hide_border=false&border_color=3d444d&bg_color=00000000
          # &layout=compact
          # &hide_title=true
          # &hide=tex,html
          # &langs_count=16
          # &hide_border=true
          # &disable_animations=true
          # &theme=${{ matrix.theme }}
          path: grs/langs-${{ matrix.theme }}.svg
          
      - name: Upload langs-${{ matrix.theme }}
        uses: actions/upload-artifact@v4
        with:
          name: langs-${{ matrix.theme }}
          path: grs

  push:
    # permissions: write-all
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Push
    needs: [generate-stats, generate-langs]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: stats-github_dark
          path: grs
      - uses: actions/download-artifact@v4
        with:
          name: stats-light
          path: grs
      - uses: actions/download-artifact@v4
        with:
          name: langs-github_dark
          path: grs
      - uses: actions/download-artifact@v4
        with:
          name: langs-light
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: grs
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
